package org.encalmo.utils

import TypeNameUtils.*

class TypeNameUtilsSpec extends munit.FunSuite {

  test("typeName") {
    assertEquals(typeName[TestEnum], "TestEnum")
    assertEquals(typeName[Order], "Order")
    assertEquals(typeName[Status], "Status")
    assertEquals(typeName[Benefit], "Benefit")
    assertEquals(typeName[Cars], "Cars")
    assertEquals(typeName[Boats], "Boats")
    assertEquals(typeName[Planes], "Planes")
    assertEquals(typeName[Airbus], "Airbus")
    assertEquals(typeName[Boeing], "Boeing")
    assertEquals(typeName[Hobby], "Hobby")
    assertEquals(typeName[Hobby.Other], "Other")
    assertEquals(typeName[Hobby.Cooking.type], "Cooking")
    assertEquals(typeName[Hobby.Other], "Other")
    assertEquals(typeName[SensitiveData[String]], "SensitiveData")
    assertEquals(typeName[Disability], "Disability")
    assertEquals(typeName[DriverLicense], "DriverLicense")
    assertEquals(typeName[PassportNumber], "PassportNumber")
    assertEquals(typeName[Option[String]], "Option")
    assertEquals(typeName[List[String]], "List")
    assertEquals(typeName[Array[String]], "Array")
    assertEquals(typeName[Hobby], "Hobby")
    assertEquals(typeName[PassportNumber], "PassportNumber")
    assertEquals(typeName[ImmigrationStatus], "ImmigrationStatus")
    assertEquals(typeName[String], "String")
    assertEquals(typeName[Int], "Int")
    assertEquals(typeName[Boolean], "Boolean")
    assertEquals(typeName[Double], "Double")
    assertEquals(typeName[Float], "Float")
    assertEquals(typeName[Long], "Long")
    assertEquals(typeName[Short], "Short")
    assertEquals(typeName[Byte], "Byte")
    assertEquals(typeName[Char], "Char")
  }

  test("valueName") {
    assertEquals(valueName[TestEnum], "testEnum")
    assertEquals(valueName[Order], "order")
    assertEquals(valueName[Status], "status")
    assertEquals(valueName[Benefit], "benefit")
    assertEquals(valueName[Cars], "cars")
    assertEquals(valueName[Boats], "boats")
    assertEquals(valueName[Planes], "planes")
    assertEquals(valueName[Airbus], "airbus")
    assertEquals(valueName[Boeing], "boeing")
    assertEquals(valueName[Hobby], "hobby")
    assertEquals(valueName[Hobby.Other], "other")
    assertEquals(valueName[Hobby.Cooking.type], "cooking")
    assertEquals(valueName[Hobby.Other], "other")
    assertEquals(valueName[SensitiveData[String]], "sensitiveDataString")
    assertEquals(valueName[Disability], "disability")
    assertEquals(valueName[DriverLicense], "driverLicense")
    assertEquals(valueName[PassportNumber], "passportNumber")
    assertEquals(valueName[Option[String]], "optionString")
    assertEquals(valueName[List[String]], "listString")
    assertEquals(valueName[Array[String]], "arrayString")
    assertEquals(valueName[Hobby], "hobby")
    assertEquals(valueName[PassportNumber], "passportNumber")
    assertEquals(valueName[ImmigrationStatus], "immigrationStatus")
    assertEquals(valueName[String], "string")
    assertEquals(valueName[Int], "int")
    assertEquals(valueName[Boolean], "boolean")
    assertEquals(valueName[Double], "double")
    assertEquals(valueName[Float], "float")
    assertEquals(valueName[Long], "long")
    assertEquals(valueName[Short], "short")
    assertEquals(valueName[Byte], "byte")
    assertEquals(valueName[Char], "char")
  }
}
